[general]
trace_instructions = false
start_pc = "0x80000000"

[system]
uart_base = "0x10000000"
disk_base = "0x90000000"
ram_base = "0x80000000"

[memory]
ram_size = "0x08000000"
controller = "DRAM"
t_cas = 15
t_ras = 35
t_pre = 15
tlb_size = 64

[pipeline]
branch_predictor = "Tournament"
btb_size = 16384
ras_size = 64

[cache.l1_i]
enabled = true
size_bytes = 131072
line_bytes = 64
ways = 8
policy = "LRU"
latency = 3
prefetcher = "NextLine"
prefetch_degree = 2
prefetch_table_size = 64

[cache.l1_d]
enabled = true
size_bytes = 131072
line_bytes = 64
ways = 8
policy = "LRU"
latency = 3
prefetcher = "NextLine"
prefetch_degree = 2
prefetch_table_size = 64

[cache.l2]
enabled = true
size_bytes = 65536
line_bytes = 64
ways = 8
policy = "LRU"
latency = 6
prefetcher = "None"
prefetch_table_size = 0
prefetch_degree = 0

[cache.l3]
enabled = false

[pipeline.perceptron]
history_length = 40
table_bits = 10
